#!/usr/bin/env bash
# Pre-commit guard: block staging of generated/derived files.
#
# Catches two categories of files that agents commonly commit by accident:
#   1. BUILD ARTIFACTS — files generated from source code (Go templ, protobuf,
#      compiled CSS, bundled JS, node_modules, vendor dirs, etc.)
#   2. RATCHET RUNTIME STATE — debate transcripts, guard results, plan.yaml, etc.
#
# Detection methods:
#   - File path patterns (e.g., *_templ.go, node_modules/, dist/)
#   - Content markers in first 10 lines (e.g., "Code generated ... DO NOT EDIT")
#   - Stack-aware inference from project.yaml (Go, Node, Python, etc.)
#
# Projects configure deny-lists in workflow.yaml under generated_file_patterns.
# Override: RATCHET_ALLOW_GENERATED=1 git commit ...
#
# Exit 0 = clean, Exit 1 = generated files detected.

set -euo pipefail

# ── Stack-agnostic generated file patterns ───────────────────────────────────
# Common across all stacks. Matched as substrings against staged file paths.
BUILTIN_PATH_PATTERNS=(
    # Ratchet runtime state
    '.ratchet/debates/'
    '.ratchet/reviews/'
    '.ratchet/scores/'
    '.ratchet/retros/'
    '.ratchet/escalations/'
    '.ratchet/guards/'
    '.ratchet/reports/'
    '.ratchet/progress/'
    '.ratchet/worktrees/'
    '.ratchet/plan.yaml'
    '.ratchet/issues/'
    '.ratchet/locks/'
    '.ratchet/archive/'
    '.claude/ratchet-scripts/'

    # Universal build artifacts — never wanted in VCS regardless of stack
    'node_modules/'
    '__pycache__/'
    '.pyc'
    '.pyo'
)

# ── Stack-agnostic content markers ───────────────────────────────────────────
# Regex patterns matched against the first 10 lines of staged files.
BUILTIN_CONTENT_MARKERS=(
    '// Code generated .* DO NOT EDIT'
    '// Code generated by .* DO NOT EDIT'
    '# Auto-generated .* do not edit'
    '# This file is auto-generated'
    '<!-- generated by'
    'THIS FILE IS AUTO-GENERATED'
    'DO NOT EDIT. This file was generated'
    'Automatically generated by'
    'Generated by .* DO NOT EDIT'
    'AUTO GENERATED FILE, DO NOT EDIT'
)

# ── Stack-specific generated file patterns ───────────────────────────────────
# Inferred from project.yaml stack. These are well-known patterns per ecosystem.
detect_stack_patterns() {
    local project_file="$1"
    [ -f "$project_file" ] || return 0

    local content
    content=$(cat "$project_file")

    # Go ecosystem
    if printf '%s' "$content" | grep -qi '\bgo\b'; then
        STACK_PATH_PATTERNS+=(
            '_templ.go'           # templ generated components
            '.pb.go'              # protobuf generated code
            '.pb.gw.go'           # grpc-gateway generated
            '_grpc.pb.go'         # grpc generated stubs
            '_enumer.go'          # enumer generated code
            '_string.go'          # stringer generated code
            '_mock.go'            # mockgen generated mocks
            '_gen.go'             # generic generated code
            'wire_gen.go'         # wire dependency injection
            '_easyjson.go'        # easyjson generated
            '_msgpack.go'         # msgpack generated
            'bindata.go'          # go-bindata generated
            'statik.go'           # statik generated
            'vendor/'             # vendored dependencies
        )
    fi

    # Node/JavaScript/TypeScript ecosystem
    if printf '%s' "$content" | grep -qiE '\b(node|javascript|typescript|react|vue|angular|next|svelte)\b'; then
        STACK_PATH_PATTERNS+=(
            'node_modules/'       # npm/yarn dependencies
            'dist/'               # build output
            '.next/'              # Next.js build
            '.nuxt/'              # Nuxt.js build
            '.svelte-kit/'        # SvelteKit build
            '.output/'            # Nitro/Nuxt output
            'build/'              # generic build output
            '.parcel-cache/'      # parcel cache
            '.turbo/'             # turborepo cache
        )
    fi

    # Python ecosystem
    if printf '%s' "$content" | grep -qi '\bpython\b'; then
        STACK_PATH_PATTERNS+=(
            '__pycache__/'        # bytecode cache
            '.pyc'                # compiled bytecode
            '*.egg-info/'         # package metadata
            '.eggs/'              # egg cache
            'dist/'               # build output
            'build/'              # build output
            '.venv/'              # virtual environment
            'venv/'               # virtual environment
        )
    fi

    # Rust ecosystem
    if printf '%s' "$content" | grep -qi '\brust\b'; then
        STACK_PATH_PATTERNS+=(
            'target/'             # cargo build output
        )
    fi

    # CSS/Frontend build tools
    if printf '%s' "$content" | grep -qiE '\b(tailwind|sass|scss|less|postcss|css)\b'; then
        STACK_PATH_PATTERNS+=(
            '.css.map'            # CSS source maps
            '.js.map'             # JS source maps
        )
    fi

    # Java/Kotlin/JVM ecosystem
    if printf '%s' "$content" | grep -qiE '\b(java|kotlin|gradle|maven)\b'; then
        STACK_PATH_PATTERNS+=(
            'build/'              # gradle build output
            'target/'             # maven build output
            '.gradle/'            # gradle cache
        )
    fi
}

# ── Load project-specific patterns from workflow.yaml ────────────────────────
load_extra_patterns() {
    local workflow_file="$1"
    [ -f "$workflow_file" ] || return 0

    # Extract generated_file_patterns.paths[] — simple line-by-line YAML parsing.
    local in_section=false in_paths=false
    while IFS= read -r line; do
        if [[ "$line" =~ ^generated_file_patterns: ]]; then
            in_section=true; in_paths=false; continue
        fi
        if $in_section && [[ "$line" =~ ^[[:space:]]+paths: ]]; then
            in_paths=true; continue
        fi
        if $in_section && [[ "$line" =~ ^[[:space:]]+content_markers: ]]; then
            in_paths=false; continue
        fi
        # Exit section on non-indented line (next top-level key)
        if $in_section && [[ "$line" =~ ^[a-z] ]]; then
            break
        fi
        if $in_paths && [[ "$line" =~ ^[[:space:]]+-[[:space:]]+(.*) ]]; then
            local val="${BASH_REMATCH[1]}"
            val="${val#\"}" ; val="${val%\"}"
            val="${val#\'}" ; val="${val%\'}"
            EXTRA_PATH_PATTERNS+=("$val")
        fi
    done < "$workflow_file"

    # Extract generated_file_patterns.content_markers[]
    in_section=false
    local in_markers=false
    while IFS= read -r line; do
        if [[ "$line" =~ ^generated_file_patterns: ]]; then
            in_section=true; in_markers=false; continue
        fi
        if $in_section && [[ "$line" =~ ^[[:space:]]+content_markers: ]]; then
            in_markers=true; continue
        fi
        if $in_section && [[ "$line" =~ ^[[:space:]]+paths: ]]; then
            in_markers=false; continue
        fi
        if $in_section && [[ "$line" =~ ^[a-z] ]]; then
            break
        fi
        if $in_markers && [[ "$line" =~ ^[[:space:]]+-[[:space:]]+(.*) ]]; then
            local val="${BASH_REMATCH[1]}"
            val="${val#\"}" ; val="${val%\"}"
            val="${val#\'}" ; val="${val%\'}"
            EXTRA_CONTENT_MARKERS+=("$val")
        fi
    done < "$workflow_file"
}

STACK_PATH_PATTERNS=()
EXTRA_PATH_PATTERNS=()
EXTRA_CONTENT_MARKERS=()

# ── Gather patterns from all sources ─────────────────────────────────────────

# Stack detection from project.yaml (root + workspaces)
detect_stack_patterns ".ratchet/project.yaml"
for ws_dir in */; do
    [ -d "$ws_dir" ] || continue
    detect_stack_patterns "${ws_dir}.ratchet/project.yaml"
done

# Custom patterns from workflow.yaml (root + workspaces)
load_extra_patterns ".ratchet/workflow.yaml"
for ws_dir in */; do
    [ -d "$ws_dir" ] || continue
    load_extra_patterns "${ws_dir}.ratchet/workflow.yaml"
done

# Combine all sources (deduplicated naturally — substring match means overlaps are harmless)
ALL_PATH_PATTERNS=(
    "${BUILTIN_PATH_PATTERNS[@]}"
    ${STACK_PATH_PATTERNS[@]+"${STACK_PATH_PATTERNS[@]}"}
    ${EXTRA_PATH_PATTERNS[@]+"${EXTRA_PATH_PATTERNS[@]}"}
)
ALL_CONTENT_MARKERS=(
    "${BUILTIN_CONTENT_MARKERS[@]}"
    ${EXTRA_CONTENT_MARKERS[@]+"${EXTRA_CONTENT_MARKERS[@]}"}
)

# ── Check staged files ───────────────────────────────────────────────────────
staged_files=$(git diff --cached --name-only --diff-filter=ACM 2>/dev/null || true)

if [ -z "$staged_files" ]; then
    exit 0
fi

violations=()

# Check path patterns — match as substring (handles workspace prefixes like monitor/)
while IFS= read -r file; do
    [ -z "$file" ] && continue
    for pattern in "${ALL_PATH_PATTERNS[@]}"; do
        if [[ "$file" == *"$pattern"* ]]; then
            violations+=("PATH  $file  (matches: $pattern)")
            break
        fi
    done
done <<< "$staged_files"

# Check content markers in staged file contents (skip binaries, skip already-flagged)
while IFS= read -r file; do
    [ -z "$file" ] && continue

    # Skip files already flagged by path check
    already_flagged=false
    for v in "${violations[@]+"${violations[@]}"}"; do
        if [[ "$v" == *"$file"* ]]; then
            already_flagged=true
            break
        fi
    done
    $already_flagged && continue

    # Read staged version of file (not working tree), skip binary files
    staged_content=$(git show ":$file" 2>/dev/null || true)
    [ -z "$staged_content" ] && continue

    # Only check first 10 lines for generated markers (they're typically at the top)
    head_content=$(printf '%s\n' "$staged_content" | head -10)
    for marker in "${ALL_CONTENT_MARKERS[@]}"; do
        if printf '%s\n' "$head_content" | grep -qiE "$marker" 2>/dev/null; then
            violations+=("CONTENT  $file  (marker: $marker)")
            break
        fi
    done
done <<< "$staged_files"

# ── Report ───────────────────────────────────────────────────────────────────
if [ ${#violations[@]} -gt 0 ]; then
    echo "================================================================"
    echo "  Ratchet: Generated/derived files detected in staged changes"
    echo "================================================================"
    echo ""
    for v in "${violations[@]}"; do
        echo "  x $v"
    done
    echo ""
    echo "These files are generated from source code or are runtime artifacts."
    echo "They should not be committed — they can be regenerated from source."
    echo ""
    echo "To fix:"
    echo "  git reset HEAD <file>          # unstage the file"
    echo "  echo '<pattern>' >> .gitignore # prevent future staging"
    echo ""
    echo "To add project-specific patterns, edit workflow.yaml:"
    echo "  generated_file_patterns:"
    echo "    paths:"
    echo "      - 'my_generated_dir/'"
    echo "    content_markers:"
    echo "      - 'Generated by MyTool'"
    echo ""
    echo "To override (if you're sure this file should be committed):"
    echo "  RATCHET_ALLOW_GENERATED=1 git commit ..."
    echo ""
    exit 1
fi

exit 0
